- name: Install nginx and is working  (state=present is optional)
  ansible.builtin.apt:
    name: nginx-core

- name: nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: copy the nginx config file and restart nginx
  ansible.builtin.copy:
    src: ../files/default
    dest: /etc/nginx/sites-available/default
  become: yes
  notify: restart nginx

- name: nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
