- name: Install or check if nginx exist
  ansible.builtin.apt:
    name: nginx-core
  notify: start nginx

- name: copy the nginx config file and restart nginx
  ansible.builtin.copy:
    src: ../files/default
    dest: /etc/nginx/sites-available/default
  become: yes
  notify: restart nginx

