- name: Install nginx  (state=present is optional)
  ansible.builtin.apt:
    name: nginx-core

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started

- name: copy the nginx config file and restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  
