- name: Install nginx
  ansible.builtin.apt:
    name: nginx-core
    state: present

- name: copy the nginx config file and restart nginx
  ansible.builtin.template:
    src: ../templates/default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
