  - name: Influxdb GPG key
    ansible.builtin.apt_key:
      url: https://repos.influxdata.com/influxdata-archive_compat.key
      keyring: /etc/apt/keyrings/influxdb.gpg

  - name: Influxdb APT repos
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/influxdb.gpg] https://repos.influxdata.com/debian stable main"

  - name: Install InfluxDB 1.8.10
    ansible.builtin.apt:
      name: influxdb=1.8.10-1
      allow_downgrade: yes

  - name: Start and enable InfluxDB service
    ansible.builtin.systemd:
      name: influxdb
      state: started
      enabled: yes
