- name: Add the Grafana APT key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Get Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana

- name: Reconfigure Grafana
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Configure datasources
  ansible.builtin.template:
    src: ../templates/datasources.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
  notify: Restart Grafana

- name: Configure dashboards
  ansible.builtin.copy:
    src: ../files/dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards
  notify: Restart Grafana

- name: send dashboard.json files
  ansible.builtin.copy:
    src: ../files/main.json
    dest: /var/lib/grafana/main.json
  notify: Restart Grafana

- name: Enable and start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
