- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    - python3-pymysql

- name: start uwsgi
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes

- name: copy the uwsgi config file
  ansible.builtin.template:
    src: ../templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: restart uwsgi

