- name: Install mysql exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter

- name: Configure MySQL exporter
  ansible.builtin.template:
    src: my.prometheus.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  no_log: true
  notify: restart mysql exporter
