- name: Download mysql-server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Download python-pymysql
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: copy the mysql config file and restart mysql server
  ansible.builtin.copy:
    src: ../files/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Start on System boot
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
