---
- name: Install bind
  ansible.builtin.apt:
    name: bind9

- name: copy the named config file
  ansible.builtin.template:
    src: bind.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
#  notify: restart bind

- name: copy the db.minecraft2.ttu config file
  ansible.builtin.template:
    src: db.{{ domain }}.j2
    dest: /var/cache/bind/db.{{ domain }}
  notify: restart bind

- name: start bind
  ansible.builtin.service:
    name: bind9
    state: started
